services:
  net:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    command: bash -eux entrypoint.sh -f net6.0
    working_dir: /src
    volumes:
      - ./6.0:/src

  nodep:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    command: bash -eux entrypoint.sh -f net6.0
    working_dir: /src
    volumes:
      - ./6.0_nodep:/src
