name: dotnet-build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
            5.0.x
            3.1.x
      - run: dotnet build ./src/SkiaSharp.QrCode/ -c Debug
      - run: dotnet build ./samples/ManualGenerate/ -c Debug
      - run: dotnet build ./samples/SimpleGenerate/ -c Debug
      # tests
      - run: dotnet test ./tests/SkiaSharp.QrCode.Tests.net31/ -c Debug
      - run: dotnet test ./tests/SkiaSharp.QrCode.Tests.net50/ -c Debug -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      - uses: codecov/codecov-action@v1
        with:
          file: ./tests/SkiaSharp.QrCode.Tests.net50/coverage.opencover.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
      # run
      - run: dotnet run --project ./samples/ManualGenerate/ManualGenerate.csproj -c Debug -f netcoreapp3.1
      - run: dotnet run --project ./samples/ManualGenerate/ManualGenerate.csproj -c Debug -f net5.0
      - run: dotnet run --project ./samples/SimpleGenerate/SimpleGenerate.csproj -c Debug -f netcoreapp3.1
      - run: dotnet run --project ./samples/SimpleGenerate/SimpleGenerate.csproj -c Debug -f net5.0
      - run: docker-compose -f ./samples/LinuxRunSamples/docker-compose.yaml up
