name: dotnet-build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip
  DOCKER_BUILDKIT: 1
  DOTNET_BUILD_CONFIG: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Build
        run: dotnet build  -c ${{ env.DOTNET_BUILD_CONFIG }}
      - name: Test
        run: dotnet test -c ${{ env.DOTNET_BUILD_CONFIG }} -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --logger GitHubActions --logger console;verbosity=normal
      - uses: codecov/codecov-action@v1
        with:
          file: ./tests/SkiaSharp.QrCode.Tests/coverage.opencover.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
        continue-on-error: true
